do-sprint-start finished

diff --git a/tasks/task-update-dependencies b/tasks/task-update-dependencies
--- a/tasks/task-update-dependencies
+++ b/tasks/task-update-dependencies
@@ -10,7 +10,6 @@ fi
 
 ## validate if we are calling from correct directory
 TASK_DIRECTORY=$(pwd)
-PARENT_ROOT="../*"
 if test -d "$TASK_DIRECTORY/lib"; then
   echo "Calling from correct directory"
   # Add lib to path
@@ -26,37 +25,14 @@ fi
 
 
 
-# DEFINE FUNCTIONS --------------------------------------------------------------------------------------------------- #
-
-#PARAM $1   _directory
-#RETURN     "true" | "false" on stdout
-isBackendProject() {
-  _directory=$1
-  if test -f "$_directory/pom.xml"; then
-    echo true
-  else
-    echo false
-  fi
-}
-
-# END DEFINE FUNCTIONS ------------------------------------------------------------------------------------------- END #
-
-
-
-
-
 # ==> MAIN LOGIC <== #
-for _dir in $PARENT_ROOT; do
-  if [ "$(isBackendProject "$_dir")" = true ]; then
-    echo "Update Dependencies: $_dir ..."
-    cd "$_dir" # Change working dir into project
-    git checkout develop
-    _gitStatus=$?
-    if [ $_gitStatus -ne 0 ]; then
-      echo ".. Cannot checkout develop branch!"
-    else
-      mvn versions:use-latest-versions -DallowAnyUpdates=false -DallowMajorUpdates=false -DallowMinorUpdates=true -DallowIncrementalUpdates=true -DprocessParent=true -DprocessDependencies=false
-      mvn versions:use-latest-versions -DallowAnyUpdates=false -DallowMajorUpdates=false -DallowMinorUpdates=true -DallowIncrementalUpdates=true -DprocessParent=false -DprocessDependencies=true
-    fi
-  fi
-done
+echo "Update Dependencies ..."
+cd .. # Change working dir into project
+git checkout develop
+_gitStatus=$?
+if [ $_gitStatus -ne 0 ]; then
+  echo ".. Cannot checkout develop branch!"
+else
+  mvn versions:use-latest-versions -DallowAnyUpdates=false -DallowMajorUpdates=false -DallowMinorUpdates=true -DallowIncrementalUpdates=true -DprocessParent=true -DprocessDependencies=false
+  mvn versions:use-latest-versions -DallowAnyUpdates=false -DallowMajorUpdates=false -DallowMinorUpdates=true -DallowIncrementalUpdates=true -DprocessParent=false -DprocessDependencies=true
+fi
