prepare do-release

diff --git a/tasks/task-precheck b/tasks/task-precheck
--- a/tasks/task-precheck
+++ b/tasks/task-precheck
@@ -10,7 +10,6 @@ fi
 
 ## validate if we are calling from correct directory
 TASK_DIRECTORY=$(pwd)
-PARENT_ROOT="../*"
 if test -d "$TASK_DIRECTORY/lib"; then
   echo "Calling from correct directory"
   # Add lib to path
@@ -46,27 +45,25 @@ isGitProject() {
 
 
 # ==> MAIN LOGIC <== #
-for _dir in $PARENT_ROOT; do
-  if [ "$(isGitProject "$_dir")" = true ]; then
-    echo "Prepare GIT project: $_dir ..."
-    cd "$_dir" # Change working dir into project
+if [ "$(isGitProject "..")" = true ]; then
+  echo "Prepare GIT project: $_dir ..."
+  cd "$_dir" # Change working dir into project
 
-    if [ "$_dir" = "../backend-stihl-lasttests" ]; then
-        echo "... skip ../backend-stihl-lasttests"
-    elif [ -z "$(git status --porcelain)" ]; then
-      if [ "$_dir" = "../bs-tsapis-ssc-pdfgenerator" ]; then
-        echo "... switch to master branch"
-        git checkout master
-      else
-        echo "... switch to develop branch"
-        git checkout develop
-      fi
-
-      echo "... update repository"
-      git pull
+  if [ "$_dir" = "../backend-stihl-lasttests" ]; then
+      echo "... skip ../backend-stihl-lasttests"
+  elif [ -z "$(git status --porcelain)" ]; then
+    if [ "$_dir" = "../bs-tsapis-ssc-pdfgenerator" ]; then
+      echo "... switch to master branch"
+      git checkout master
     else
-      echo "... ERROR: git repository $_dir is not clean!"
-      exit 255
+      echo "... switch to develop branch"
+      git checkout develop
     fi
+
+    echo "... update repository"
+    git pull
+  else
+    echo "... ERROR: git repository $_dir is not clean!"
+    exit 255
   fi
-done
+fi
